// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO
    todos (
        id,
        created_at,
        updated_at,
        title,
        description,
        user_id
    )
VALUES (
        gen_random_uuid (),
        NOW(),
        NOW(),
        $1,
        $2,
        $3
    ) RETURNING id, created_at, updated_at, title, description, user_id
`

type CreateTodoParams struct {
	Title       string
	Description string
	UserID      uuid.UUID
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Title, arg.Description, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1 AND user_id = $2
`

type DeleteTodoParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, created_at, updated_at, title, description, user_id FROM todos WHERE id = $1
`

func (q *Queries) GetTodoByID(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const getTodosByUserID = `-- name: GetTodosByUserID :many
SELECT id, created_at, updated_at, title, description, user_id
FROM todos
WHERE
    user_id = $1
ORDER BY updated_at DESC
LIMIT $2
OFFSET
    $3
`

type GetTodosByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetTodosByUserID(ctx context.Context, arg GetTodosByUserIDParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosCountByUserID = `-- name: GetTodosCountByUserID :one
SELECT COUNT(*) FROM todos where user_id = $1
`

func (q *Queries) GetTodosCountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTodosCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET
    title = $3,
    description = $4,
    updated_at = NOW()
WHERE
    id = $1
    AND user_id = $2 RETURNING id, created_at, updated_at, title, description, user_id
`

type UpdateTodoParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description string
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}
